package enumeration;

public enum Header {
	JOIN, LOGIN,
	INSERT_FRIEND, DELETE_FRIEND,
	INSERT_SCHEDULE, UPDATE_SCHEDULE, DELETE_SCHEDULE,
	SHARE, UNSHARE,
	
	JOIN_ID_ALREADY_EXIST,
	LOGIN_NO_ID, LOGIN_WRONG_PW,
	
	SEARCH_FRIEND,
	
	FAIL_TO_JOIN, FAIL_TO_LOGIN,
	FAIL_TO_INSERT_SCHEDULE, FAIL_TO_UPDATE_SCHEDULE, FAIL_TO_DELETE_SCHEDULE, 
	FAIL_TO_INSERT_FRIEND, FAIL_TO_DELETE_FRIEND, 
	FAIL_TO_SHARE, FAIL_TO_UNSHARE,
	FAIL_TO_SEARCH_FRIEND,
	
	FAIL_TO_SELECT_SCHEDULE, SUCCESS_TO_SELECT_SCHEDULE,
	FAIL_TO_SELECT_SHARING, SUCCESS_TO_SELECT_SHARING,
	FAIL_TO_SELECT_FRIEND, SUCCESS_TO_SELECT_FRIEND;
	
	public static Header getHeader(String name) {
		for(Header h : values())
			if(h.name().equals(name))	return h;
		return null;
	}
}