package enumeration;

public enum Header {
	JOIN, LOGIN,
	SELECT_SCHEDULE_BY_YMD, SELECT_SCHEDULE_BY_KEYWORD,
	SELECT_FRIENDS, SELECT_FRIEND, INSERT_FRIEND, DELETE_FRIEND,
	INSERT_SCHEDULE, UPDATE_SCHEDULE, DELETE_SCHEDULE,
	INSERT_SHARING, DELETE_SHARING,
	
	JOIN_SUCCESS, JOIN_ID_ALREADY_EXIST,
	LOGIN_SUCCESS, LOGIN_NO_ID, LOGIN_WRONG_PW,
	ALARM_INSERT_FRIEND, ALARM_DELETE_FRIEND, ALARM_SHARE, ALARM_UNSHARE,
	
	FAIL_TO_JOIN, FAIL_TO_LOGIN,
	FAIL_TO_SELECT_SCHEDULE, FAIL_TO_INSERT_SCHEDULE, FAIL_TO_UPDATE_SCHEDULE, FAIL_TO_DELETE_SCHEDULE,
	FAIL_TO_INSERT_FRIEND, FAIL_TO_DELETE_FRIEND, FAIL_TO_SELECT_FRIEND, FAIL_TO_SELECT_FRIENDS,
	FAIL_TO_SHARE, FAIL_TO_UNSHARE;
	
	public static Header getHeader(String name) {
		for(Header h : values())
			if(h.name().equals(name))	return h;
		return null;
	}
}